/**
 * Script to automatically update .env with local Supabase credentials
 * Run with: pnpm run env:local
 * 
 * Prerequisites:
 * - Local Supabase must be running (npx supabase start)
 * - This script reads credentials from `npx supabase status`
 * - Supabase commands are run from root directory (where supabase/ folder is)
 * - .env file is updated in cribbage-core directory
 */

import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';

// .env file is in cribbage-core directory
const ENV_FILE = path.join(process.cwd(), '.env');
// Supabase commands should be run from root directory (where supabase/ folder is)
const ROOT_DIR = path.join(process.cwd(), '..');

interface SupabaseStatus {
  apiUrl: string;
  anonKey: string;
  serviceRoleKey: string;
  dbUrl: string;
}

function getSupabaseStatus(): SupabaseStatus {
  try {
    // Run supabase status from root directory where supabase/ folder is located
    const output = execSync('npx supabase status', {
      encoding: 'utf-8',
      stdio: ['pipe', 'pipe', 'pipe'],
      cwd: ROOT_DIR,
    });

    // Parse the status output (handles both old and new CLI formats)
    const lines = output.split('\n');

    // Try new format first (table format with "Project URL", "Publishable", "Secret", "URL")
    const getValueFromTable = (label: string): string | null => {
      // Look for lines like "│ Project URL    │ http://127.0.0.1:54321              │"
      const regex = new RegExp(`│\\s+${label}[^│]*│\\s+([^│]+)`, 'i');
      for (const line of lines) {
        const match = line.match(regex);
        if (match) {
          return match[1].trim();
        }
      }
      return null;
    };

    // Try old format (key: value format)
    const getValueFromKeyValue = (prefix: string): string | null => {
      const line = lines.find((l) => l.trim().startsWith(prefix));
      if (!line) return null;
      const match = line.match(new RegExp(`${prefix}:\\s*(.+)`));
      return match ? match[1].trim() : null;
    };

    // Extract values (try new format first, fallback to old format)
    const apiUrl =
      getValueFromTable('Project URL') || getValueFromKeyValue('API URL');
    const anonKey =
      getValueFromTable('Publishable') || getValueFromKeyValue('anon key');
    const serviceRoleKey =
      getValueFromTable('Secret') || getValueFromKeyValue('service_role key');
    const dbUrl =
      getValueFromTable('URL')?.split('│')[0]?.trim() ||
      getValueFromKeyValue('DB URL');

    if (!apiUrl || !anonKey || !serviceRoleKey || !dbUrl) {
      throw new Error(
        'Could not parse Supabase status output. Missing required fields.',
      );
    }

    return {
      apiUrl,
      anonKey,
      serviceRoleKey,
      dbUrl,
    };
  } catch (error) {
    console.error(
      '❌ Failed to get Supabase status. Is local Supabase running?',
    );
    console.error('   Run: npx supabase start');
    if (error instanceof Error) {
      console.error(`   Error: ${error.message}`);
    }
    process.exit(1);
  }
}

function updateEnvFile(status: SupabaseStatus): void {
  let content: string;

  if (fs.existsSync(ENV_FILE)) {
    content = fs.readFileSync(ENV_FILE, 'utf-8');
  } else {
    // Create new .env file if it doesn't exist
    content = `# Cribbage Core Environment Variables
# Auto-generated by update-local-env.ts script

# Server Configuration
PORT=3002
WEB_APP_ORIGIN=http://localhost:8081
WEBSOCKET_AUTH_TOKEN="a-dubs-mac-token"
OVERRIDE_START_SCORE=
ENABLE_RESTART_GAME=true

# Supabase Configuration
SUPABASE_URL=
SUPABASE_ANON_KEY=
SUPABASE_SERVICE_ROLE_KEY=
SUPABASE_AUTH_ENABLED=true
SUPABASE_LOBBIES_ENABLED=true
`;
  }

  // Define the replacements for cribbage-core .env format
  const replacements: Record<string, string> = {
    SUPABASE_URL: status.apiUrl,
    SUPABASE_ANON_KEY: status.anonKey,
    SUPABASE_SERVICE_ROLE_KEY: status.serviceRoleKey,
  };

  // Update each value
  for (const [key, value] of Object.entries(replacements)) {
    // Match the key followed by = and capture everything until end of line
    // Only match uncommented lines (not starting with #)
    const regex = new RegExp(`^(${key}=).*$`, 'm');
    if (regex.test(content)) {
      content = content.replace(regex, `$1${value}`);
    } else {
      // If key doesn't exist, add it to the Supabase Configuration section
      const supabaseSectionRegex = /# Supabase Configuration.*\n/;
      if (supabaseSectionRegex.test(content)) {
        // Find the last Supabase key and add after it
        const lines = content.split('\n');
        let insertIndex = -1;
        for (let i = 0; i < lines.length; i++) {
          if (lines[i].startsWith('SUPABASE_')) {
            insertIndex = i;
          } else if (
            insertIndex !== -1 &&
            !lines[i].startsWith('SUPABASE_') &&
            lines[i].trim() !== ''
          ) {
            break;
          }
        }
        if (insertIndex !== -1) {
          lines.splice(insertIndex + 1, 0, `${key}=${value}`);
          content = lines.join('\n');
        } else {
          // Fallback: append after Supabase Configuration comment
          content = content.replace(
            supabaseSectionRegex,
            `$&${key}=${value}\n`,
          );
        }
      } else {
        // If no section exists, append to end
        content += `\n${key}=${value}`;
      }
    }
  }

  fs.writeFileSync(ENV_FILE, content);
  console.log('✅ Updated .env with local Supabase credentials:');
  console.log(`   API URL:     ${status.apiUrl}`);
  console.log(`   Anon Key:    ${status.anonKey.slice(0, 20)}...`);
  console.log(`   Service Key: ${status.serviceRoleKey.slice(0, 20)}...`);
  console.log(`   DB URL:      ${status.dbUrl}`);
}

function main() {
  console.log('🔄 Fetching local Supabase credentials...\n');

  const status = getSupabaseStatus();
  updateEnvFile(status);

  console.log(
    '\n✨ Done! Your .env is now configured for local development.',
  );
  console.log('   You can now test migrations with: npx supabase migration up');
}

main();
